shopping_cart/config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users,  controllers: { sessions: "users/sessions", registrations: "users/registrations" }
 
  root "products#index"
  resources :products
  resources :shipping_details
  get "/cards/:shipping_details_id", to: "cards#index", as: :select_card
  resources :cards
  get "/user_items", to: "products#view_user_items", as: :view_user_items
  get "/categories/:category", to: "products#category", as: :category
  get "/cart", to: "carts#view", as: :view_cart
  get "/cart/clear", to: "carts#clear", as: :clear_cart
  post "/cart/:id", to: "cart_items#add", as: :cart
  put "/cart_item/increment/:id", to: "cart_items#increment", as: :increment
  put "/cart_item/decrement/:id", to: "cart_items#decrement", as: :decrement
  delete "/cart_item/destroy/:id", to: "cart_items#destroy", as: :destroy_cart_item
  post "/order", to: "orders#create", as: :create_order
  get "/orders", to: "orders#index", as: :orders
  get "/orders/:id", to: "orders#show", as: :view_order
  get "/ordered_items/:id", to: "ordered_items#show", as: :view_ordered_item
  get "*path", to: "products#index"
end

shopping_cart/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  mount_uploader :file, FileUploader
  
  validates :description, presence: true, length: { minimum: 10 }
  validates :price, presence: true, numericality: { only_float: true }
  validates :available_quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :file, presence: true
end

shopping_cart/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :category]
  def index
   @products = Product.all
  end
  
  def new
    @product = current_user.products.new
  end

  def create
    @product = current_user.products.new(product_params)
    redirect_to category_path(@product.category) and return if @product.save
    render :new
  end
  
  def show
    @product = current_user.products.find_by id: params[:id]
  end

  def edit
    @product = current_user.products.find_by id: params[:id]
  end

  def update
    @product = current_user.products.find_by id: params[:id]
    redirect_to product_path and return if @product.update(product_params)
    render :edit
  end

  def view_user_items
    @items = current_user.products.all
  end

  def category
    @category = params[:category]
    @category_products = Product.where(category: @category)
  end

  def destroy
    @product = current_user.products.find_by id: params[:id]
    @product.destroy
  end
  
  private
    def product_params
      params.require(:product).permit(:description, :price, :category, :return_or_replacement_applicable_days, :file, :available_quantity).merge(seller_name: current_user.name)
    end
end

shopping_cart/app/helpers/products_helper.rb
module ProductsHelper
end

shopping_cart/app/views/products/_form.html.erb
<%= form_with model:product do |form| %>
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% product.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div> 
    <% end %>
  </div>
  
  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
    <% product.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :category %><br>
    <%= form.select :category, ['clothes', 'mobiles', 'electronics'] %>
  </div>
  
    <div>
    <%= form.label :available_quantity %><br>
    <%= form.text_field :available_quantity %>
    <% product.errors.full_messages_for(:available_quantity).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div> 
  
  <div>
    <%= form.label :return_or_replacement_applicable_days %><br>
    <%= form.select :return_or_replacement_applicable_days, options_for_select(0..30) %>
  </div>  

  <div>
    <%= form.label :file %><br>
    <%= form.file_field :file %>
    <% product.errors.full_messages_for(:file).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>  

  <div>
    <%= form.submit I18n.t(:submit) %>
  </div>
<% end %>

shopping_cart/app/views/products/category.html.erb
<h1><%= @category %></h1>
<%# session.destroy %>
<% if @category_products.empty? %>
  <p>No items here right now</p>
<%end%>
<% @category_products.each do |product| %>
  <div>
    <p><%= product.description %></p>
    <p>&#8377;<%= product.price %></p>
    <img src="<%= product.file %>"></img>
    <p>Return or replace within <%= product.return_or_replacement_applicable_days %> days</p>
    <p>Seller Name: <%= product.seller_name %></p>
   
    <% if user_signed_in? and product.user_id == current_user.id %>
      <%= button_to I18n.t('buttons.edit'), edit_product_path(product.id), method: :get %>
    <% elsif (user_signed_in? and current_user.cart_items.find_by product_id: product.id)  or (!session[:items].nil? and session[:items].has_key? product.id.to_s) %>
     <%= button_to I18n.t('buttons.cart'), view_cart_path, method: :get %>
    <% else %>
      <% if product.available_quantity > 0 %>
        <%=  button_to I18n.t('buttons.add_to_cart'), cart_path(product.id), remote: true %>
      <% else %>
        <p><i>Out of stocks</i></p>
      <%end%>
    <%end%>   
  </div>
<%end%>

shopping_cart/app/views/products/edit.html.erb
<%= render "form", product :@product %>
<br>
<%= button_to 'buttons.logout', destroy_user_session_path, method: :delete %>

shopping_cart/app/views/products/index.html.erb
<h2>Select from below categories</h2>
<%= button_to "Clothes", category_path(category: "clothes"), method: :get %><br>
<%= button_to "Mobiles", category_path(category: "mobiles"), method: :get %><br>
<%= button_to "Electronics", category_path(category: "electronics"), method: :get %><br>
<%= button_to I18n.t('buttons.cart'), view_cart_path, method: :get %><br>
<% if user_signed_in? %>
  <%= button_to I18n.t('buttons.sell_items'), new_product_path, method: :get %><br>
  <%= button_to I18n.t('buttons.my_items'), view_user_items_path, method: :get %><br>
  <%= button_to I18n.t('buttons.my_orders'), orders_path, method: :get %><br> 
  <%= button_to I18n.t('buttons.logout'), destroy_user_session_path, method: :delete %>
<% else %>
  <%= button_to I18n.t('buttons.login'), new_user_session_path, method: :get %>  
<%end%>

shopping_cart/app/views/products/new.html.erb
<%= render "form", product :@product %>
<br>
<%= button_to I18n.t('buttons.logout'), destroy_user_session_path, method: :delete %>

shopping_cart/app/views/products/show.html.erb
  <p><%= @product.description %></p>
  <p>&#8377;<%= @product.price %></p>
  <img src="<%= @product.file %>"></img>
  <p>Available quantity: <%= @product.available_quantity %></p>
  <p>Return or replace within <%= @product.return_or_replacement_applicable_days %> days</p>
  <p>Seller Name: <%= @product.seller_name %></p>
  <br>
  <%= button_to I18n.t('buttons.edit'), edit_product_path(@product.id), method: :get %>
 

shopping_cart/app/views/products/view_user_items.html.erb
<h1>My items</h1>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.description, product_path(item.id), method: :get %></li>
  <%end%>
</ul>