shopping_cart/config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users,  controllers: { sessions: "users/sessions", registrations: "users/registrations" }
 
  root "products#index"
  resources :products
  resources :shipping_details
  get "/cards/:shipping_details_id", to: "cards#index", as: :select_card
  resources :cards
  get "/user_items", to: "products#view_user_items", as: :view_user_items
  get "/categories/:category", to: "products#category", as: :category
  get "/cart", to: "carts#view", as: :view_cart
  get "/cart/clear", to: "carts#clear", as: :clear_cart
  post "/cart/:id", to: "cart_items#add", as: :cart
  put "/cart_item/increment/:id", to: "cart_items#increment", as: :increment
  put "/cart_item/decrement/:id", to: "cart_items#decrement", as: :decrement
  delete "/cart_item/destroy/:id", to: "cart_items#destroy", as: :destroy_cart_item
  post "/order", to: "orders#create", as: :create_order
  get "/orders", to: "orders#index", as: :orders
  get "/orders/:id", to: "orders#show", as: :view_order
  get "/ordered_items/:id", to: "ordered_items#show", as: :view_ordered_item
  get "*path", to: "products#index"
end

shopping_cart/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, except: [:view]
  def view
    if user_signed_in?
      merge_session_cart
    end
  end

  def merge_session_cart
    if session[:items] 
      session[:items].each do |item_id,item| 
        product_details = item[I18n.t('models.attributes.product_details')] 
        if !(current_user.cart_items.find_by product_id: product_details[I18n.t('models.attributes.id')]) 
          cart_item = current_user.cart_items.new 
          cart_item.description = product_details[I18n.t('models.attributes.description')] 
          cart_item.price = product_details[I18n.t('models.attributes.price')] 
          cart_item.file = product_details[I18n.t('models.attributes.file')][I18n.t('models.attributes.url')] 
          cart_item.return_or_replacement_applicable_days = product_details[I18n.t('models.attributes.return_replacement')] 
          cart_item.seller_name = product_details[I18n.t('models.attributes.seller_name')] 
          cart_item.product_id = product_details[I18n.t('models.attributes.id')] 
          cart_item.available_quantity = product_details[I18n.t('models.attributes.available_quantity')] 
          cart_item.quantity = item[I18n.t('models.attributes.quantity')] 
          cart_item.save! 
        end
      end
      session[:items] = nil
    end
  end

  def clear 
    current_user.cart_items.destroy_all
  end

end

shopping_cart/app/helpers/cart_helper.rb
module CartHelper
end

shopping_cart/app/views/carts/clear.js.erb
while(document.getElementById("container").firstChild){
  document.getElementById("container").removeChild(document.getElementById("container").firstChild);
}

shopping_cart/app/views/carts/view.html.erb
<h2>Cart</h2>
<% session[:total_amount] = 0.0 %>
<% session[:shipping_charges] = 40.0 %>
<% if user_signed_in? %>
  <% if current_user.cart_items.all.size == 0 %>
    <p>cart is empty</p>
  <% else %>
    <% cart_items = current_user.cart_items.all %>
    <div id = "container">
      <% cart_items.each do |cart_item| %>
        <div id = "div-<%= cart_item.id %>">
          <p><%= cart_item.description %></p>
          <p><%= cart_item.price %></p>
          <img src="<%= cart_item.file %>"></img>
          <p id = "quantity-<%= cart_item.id %>">quantity:<%= cart_item.quantity %></p>
          <%= button_to "+", increment_path(cart_item.id), method: :put, remote: true %>
          <%= button_to "-", decrement_path(cart_item.id), method: :put, remote: true %>
          <%= button_to I18n.t('buttons.remove_item'), destroy_cart_item_path(cart_item.id), method: :delete, remote: true %>
          <% session[:total_amount] += cart_item.price * cart_item.quantity %>
        </div>
      <%end%>
      <b>Total Amount : <p id="total_amount"><%= session[:total_amount] %></p></b> 
      <p>Shipping charges : <%= session[:shipping_charges] %></p> 
      <%= button_to I18n.t('buttons.clear_cart'), clear_cart_path, method: :get, remote: true %>
      <%= button_to I18n.t('buttons.proceed_to_buy'), shipping_details_path, method: :get %>
    </div> 
  <%end%>  
<% else %>
  <% if session[:items].nil? %>
    <p>cart is empty</p>
  <% else %>
    <div id = "container">
      <% session[:items].each do |item_id,item| %>
        <div id = "div-<%= item_id %>">
        <% product_details = item[I18n.t('models.attribute.product_details')] %>
          <p><%= product_details[I18n.t('models.attribute.description')] %></p>
          <p><%= product_details[I18n.t('models.attribute.price')] %></p>
          <img src="<%= product_details[I18n.t('models.attribute.file')][I18n.t('models.attribute.url')] %>"></img>
          <p id = "quantity-<%= item_id %>">quantity:<%= item[I18n.t('models.attribute.quantity')] %></p>
          <%= button_to 'buttons.increase', increment_path(item_id), method: :put, remote: true %>
          <%= button_to 'buttons.decrease', decrement_path(item_id), method: :put, remote: true %>
          <%= button_to I18n.t('buttons.remove_item'), destroy_cart_item_path(item_id), method: :delete, remote: true %>
          <% session[:total_amount] += product_details[I18n.t('models.attribute.price')].to_f * item[I18n.t('models.attribute.quantity')].to_f %>
        </div>
        <br>
      <%end%>
      <b>Total Amount : <p id="total_amount"><%= session[:total_amount] %></p></b>
      <%= button_to I18n.t('buttons.clear_cart'), clear_cart_path, method: :get, remote: true %>
      <%= button_to I18n.t('buttons.proceed_to_buy'), shipping_details_path, method: :get %>
    <%end%> 
  </div>  
<%end%>