shopping_cart/config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users,  controllers: { sessions: "users/sessions", registrations: "users/registrations" }
 
  root "products#index"
  resources :products
  resources :shipping_details
  get "/cards/:shipping_details_id", to: "cards#index", as: :select_card
  resources :cards
  get "/user_items", to: "products#view_user_items", as: :view_user_items
  get "/categories/:category", to: "products#category", as: :category
  get "/cart", to: "carts#view", as: :view_cart
  get "/cart/clear", to: "carts#clear", as: :clear_cart
  post "/cart/:id", to: "cart_items#add", as: :cart
  put "/cart_item/increment/:id", to: "cart_items#increment", as: :increment
  put "/cart_item/decrement/:id", to: "cart_items#decrement", as: :decrement
  delete "/cart_item/destroy/:id", to: "cart_items#destroy", as: :destroy_cart_item
  post "/order", to: "orders#create", as: :create_order
  get "/orders", to: "orders#index", as: :orders
  get "/orders/:id", to: "orders#show", as: :view_order
  get "/ordered_items/:id", to: "ordered_items#show", as: :view_ordered_item
  get "*path", to: "products#index"
end

shopping_cart/app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  validates :card_owner, presence: true
  validates :card_number, presence: true, length: { is:16 }
  validates :cvv, presence: true, length: { is: 3 }
  validates :expiry_date, presence: true
  validate :is_valid_card_number
  validate :is_valid_cvv
  validate :is_valid_expiry_date

  def is_valid_card_number
    return if card_number.match?(/\A\d{16}\Z/)
    errors.add(:card_number, I18n.t('errors.not_valid'))
  end

  def is_valid_cvv
    return if cvv.match?(/\A\d{3}\Z/)
    errors.add(:cvv, I18n.t('errors.not_valid'))
  end
  
  def is_valid_expiry_date
    return if expiry_date.match?(/\A(0[5-9]|10|11|12)\/20[2-9][1-9]\Z/)
    errors.add(:expiry_date, I18n.t('errors.not_valid'))
  end

end

shopping_cart/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  def index
    session[:shipping_details_id] = params[:shipping_details_id]
  end

  def new
    @card = current_user.cards.new
  end

  def create
    @card = current_user.cards.new(card_params)
    redirect_to cards_path and return if @card.save
    render :new
  end

  def edit
    @card = current_user.cards.find_by id: params[:id]
  end

  def update
    @card = current_user.cards.find_by id: params[:id]
    redirect_to cards_path and return if @card.update(card_params)
    render :new
  end
  
  def destroy
    @card = current_user.cards.find_by id: params[:id]
    @card.destroy
  end

  private
    def card_params
      params.require(:card).permit(:card_owner, :card_number, :cvv, :expiry_date, :shipping_details_id)
    end
end

shopping_cart/app/helpers/card_helper.rb
module CardHelper
end

shopping_cart/app/views/cards/_form.html.erb
<%= form_with model:card do |form| %>
  <div>
    <%= form.label :card_owner %><br>
    <%= form.text_field :card_owner %>
    <% card.errors.full_messages_for(:card_owner).each do |message| %>
      <div><%= message %></div> 
    <% end %>
  </div>
  
  <div>
    <%= form.label :card_number %><br>
    <%= form.text_field :card_number %>
    <% card.errors.full_messages_for(:card_number).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   <div>
    <%= form.label :cvv %><br>
    <%= form.text_field :cvv %>
    <% card.errors.full_messages_for(:cvv).each do |message| %>
      <div><%= message %></div> 
    <% end %>
  </div>

  <div>
    <%= form.label :expiry_date %><br>
    <%= form.text_field :expiry_date %>
    <% card.errors.full_messages_for(:expiry_date).each do |message| %>
      <div><%= message %></div> 
    <% end %>
  </div>
  
 <div>
    <%= form.submit I18n.t('buttons.submit') %>
  </div>
<% end %>

shopping_cart/app/views/cards/edit.html.erb
<h1>Edit Card</h1>
<%= render 'form', card:@card %>

shopping_cart/app/views/cards/index.html.erb
<p>Amount to pay : <%= session[:total_amount] + session[:shipping_fee] %></p>
<% if current_user.cards.all.size > 0 %>
  <h3>Select from below debit cards</h3>
  <% current_user.cards.all.each do |card| %>
    <div>
      <p><%= card.card_owner %></p>
      <p><%= '*'*12 %><%= card.card_number[12..] %></p>
      <%= button_to I18n.t('buttons.select_proceed'), create_order_path(shipping_details_id: session[:shipping_details_id], card_id: card.id), method: :post %><br>
    </div>
  <%end%>  
<%end%>
<%= button_to I18n.t('buttons.new_card'), new_card_path, method: :get %>  

shopping_cart/app/views/cards/new.html.erb
<h1>New Card</h1>
<%= render 'form', card:@card %>